book:
    resource: "@BookBundle/Controller/"
    type:     annotation
    prefix:   /

nfq_weather:
    resource: "@NfqWeatherBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
